name: mingw

## 手动调度
on: workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile.mingw.share
        context: .
        push: true
        tags: lzh1104/php-rc:aria2c-mingw-share
